// Generated by gencpp from file iiwa_msgs/SetPathParameters.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_SETPATHPARAMETERS_H
#define IIWA_MSGS_MESSAGE_SETPATHPARAMETERS_H

#include <ros/service_traits.h>


#include <iiwa_msgs/SetPathParametersRequest.h>
#include <iiwa_msgs/SetPathParametersResponse.h>


namespace iiwa_msgs
{

struct SetPathParameters
{

typedef SetPathParametersRequest Request;
typedef SetPathParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPathParameters
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::SetPathParameters > {
  static const char* value()
  {
    return "960e33fb145e93219db644650cd367e4";
  }

  static const char* value(const ::iiwa_msgs::SetPathParameters&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::SetPathParameters > {
  static const char* value()
  {
    return "iiwa_msgs/SetPathParameters";
  }

  static const char* value(const ::iiwa_msgs::SetPathParameters&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::SetPathParametersRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetPathParameters > 
template<>
struct MD5Sum< ::iiwa_msgs::SetPathParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetPathParameters >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPathParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetPathParametersRequest> should match 
// service_traits::DataType< ::iiwa_msgs::SetPathParameters > 
template<>
struct DataType< ::iiwa_msgs::SetPathParametersRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetPathParameters >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPathParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::SetPathParametersResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetPathParameters > 
template<>
struct MD5Sum< ::iiwa_msgs::SetPathParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetPathParameters >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPathParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetPathParametersResponse> should match 
// service_traits::DataType< ::iiwa_msgs::SetPathParameters > 
template<>
struct DataType< ::iiwa_msgs::SetPathParametersResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetPathParameters >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPathParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_SETPATHPARAMETERS_H
