(cl:defpackage iiwa_msgs-srv
  (:use )
  (:export
   "CONFIGURESMARTSERVO"
   "<CONFIGURESMARTSERVO-REQUEST>"
   "CONFIGURESMARTSERVO-REQUEST"
   "<CONFIGURESMARTSERVO-RESPONSE>"
   "CONFIGURESMARTSERVO-RESPONSE"
   "SETPATHPARAMETERS"
   "<SETPATHPARAMETERS-REQUEST>"
   "SETPATHPARAMETERS-REQUEST"
   "<SETPATHPARAMETERS-RESPONSE>"
   "SETPATHPARAMETERS-RESPONSE"
   "TIMETODESTINATION"
   "<TIMETODESTINATION-REQUEST>"
   "TIMETODESTINATION-REQUEST"
   "<TIMETODESTINATION-RESPONSE>"
   "TIMETODESTINATION-RESPONSE"
  ))

